### ISSUE TITLE
Null Exception when running cucumber options tags that doesn't match any existing tag.

### ISSUE THREAD

**Issue by MiguelPanadero** [serenity-bdd/serenity-cucumber#104]
I am receiving the following exception, when I am passing a tags configuration that doesn't match any tag, i.e -Dcucumber.options="--tags @nothing": 
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE! - in com.company.cucumber.features.MyFeatures
com.company.cucumber.features.MyFeatures  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1535)
        at net.thucydides.core.steps.StepEventBus.eventBusFor(StepEventBus.java:59)
        at cucumber.runtime.formatter.SerenityReporter.assureTestSuiteFinished(SerenityReporter.java:615)
        at cucumber.runtime.formatter.SerenityReporter.handleTestRunFinished(SerenityReporter.java:313)
        at cucumber.runtime.formatter.SerenityReporter.lambda$new$6(SerenityReporter.java:135)
        at cucumber.runner.EventBus.send(EventBus.java:28)
        at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:109)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

I am using cucumber-serenity 1.6.4 and serenity core 1.7.

Thanks for your help.

Miguel.

**Comment by cliviu** [comment]
please see https://github.com/serenity-bdd/serenity-core/issues/1030. It should be fixed in the current version

**Comment by MiguelPanadero** [comment]
@wakaleo it is working as expected with those versions, thank you very much.

**Comment by dgracehmh** [comment]
@MiguelPanadero how did you get access to serenity-cucumber 1.6.5? it's not on maven yet as far as i can see?

**Comment by MiguelPanadero** [comment]
@dgracehmh is already accessible in maven, but yep you are right is not listed on the MVN repository, however I configured the dependency and it was downloaded
