### ISSUE TITLE
The same currentScenarioId is used into different features when Scenario Outline name is same

### ISSUE THREAD

**Issue by ereticul** [serenity-bdd/serenity-cucumber#12]
Hi John,

I've just encountered a null pointer exception when executing this java class:
@CucumberOptions(features="src/test/resources/samples/calculator/")
public class BasicArithemticScenario {}

As a result, three features would be executed: samples/calculator:
(1) basic_arithmetic.feature
(2) basic_arithmetic_with_tables.feature
(3) basic_arithmetic_with_tables_and_background.feature

and (2) and (3) features has the same scenario outline name: Many additions

So, the (3) feature would be resulted with an error/ exception:
java.lang.NullPointerException
	at net.serenitybdd.cucumber.SerenityReporter.addTableRowsTo(SerenityReporter.java:354)
	at net.serenitybdd.cucumber.SerenityReporter.examples(SerenityReporter.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

So, we need to reset the currentScenarioId for every new Scenario Outline which is going to be executed.

My fix:
```javascript
@Override
    public void scenarioOutline(ScenarioOutline scenarioOutline) {
        addingScenarioOutlineSteps = true;
       currentScenarioId = "";
    }
```

On next re-run of BasicArithemticScenario.java (as above), the features would be run successfully.

**Comment by ereticul** [comment]
Hi John, 

Even if my lowly fix (as above), I was playing further I noticed that (3rd) feature contains the test steps of (2nd) feature, that's due that not even the scenario outline name is same but even the feature name is the same, and it twisted the results.

Previously I've tried to fix in this way: 
```javascript
private String scenarioIdFrom(String scenarioIdOrExampleId) {
        String[] idElements = scenarioIdOrExampleId.split(";");
        return (idElements.length >= 2) ? String.format("%s;%s", idElements[0], idElements[1]) : "";
    } 
```

as a result, the scenario id would look like: basic-arithmetic;many-additions.
But I noticed that won't work as well, because we can have the same feature name.Then I remembered that there was a fix if NO feature name provided, then the feature file name is used instead, and whereas it could be applied here the defaultfeatureId, like: 

```javascript
private String scenarioIdFrom(String scenarioIdOrExampleId) {
        String[] idElements = scenarioIdOrExampleId.split(";");
        return (idElements.length >= 2) ? String.format("%s;%s", defaultFeatureId, idElements[1]) : "";
    }
```

That fix would ensure that the extracted scenarioId is unique even from scenario either from an example.

I would make a pull request with code changes. Please have a look then.

-Andy
