### ISSUE TITLE
Serenity Cucumber: First scenario fails not executing other scenarios

### ISSUE THREAD

**Issue by vi123ch** [serenity-bdd/serenity-cucumber#128]
Hello,

I have multiple feature files and each feature file has multiple scenarios. If a scenario is failed, its not executing the next scenarios of the same feature file.

<serenity.version>1.9.0-rc.3</serenity.version>
		<serenity.maven.version>1.9.0-rc.3</serenity.maven.version>
		<serenity.cucumber.version>1.6.10</serenity.cucumber.version>

Version used.My driver is provided in serenity.properties file as 

webdriver.driver=ie
webdriver.ie.driver=\\IEDriverServer.exe, 
I am using Selenium grid to run these tests at the end.

 Any help please Urgent!!!!

**Comment by wakaleo** [comment]
Cucumber scenarios are independent, so when one fails, the others should normally be executed. Are you getting any special error message?

**Comment by vi123ch** [comment]
Thanks for your quick reply. 
I have this error message:

java.lang.NoSuchMethodError: net.thucydides.core.model.TestOutcome.testStepWithDescription(Ljava/lang/String;)Lcom/google/common/base/Optional;
	at cucumber.runtime.formatter.SerenityReporter.errorOrFailureRecordedForStep(SerenityReporter.java:743)
	at cucumber.runtime.formatter.SerenityReporter.failed(SerenityReporter.java:722)
	at cucumber.runtime.formatter.SerenityReporter.recordStepResult(SerenityReporter.java:683)
	at cucumber.runtime.formatter.SerenityReporter.handleResult(SerenityReporter.java:673)
	at cucumber.runtime.formatter.SerenityReporter.handleTestStepFinished(SerenityReporter.java:276)
	at cucumber.runtime.formatter.SerenityReporter.lambda$new$4(SerenityReporter.java:114)
	at cucumber.runner.EventBus.send(EventBus.java:28)
	at cucumber.api.TestStep.run(TestStep.java:90)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:117)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:55)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:126)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by wakaleo** [comment]
That's a dependency conflict error. Try with the latest version of serenity-cucumber (1.6.13)

**Comment by vi123ch** [comment]
Yes solved my issue thanks :)
