### ISSUE TITLE
FreeMarker error after integrating serenity with jira

### ISSUE THREAD

**Issue by kamit78** [serenity-bdd/serenity-cucumber#77]
Hi,

I'm getting following error on integrating serenity with jira. 

SEVERE: Error executing FreeMarker template
FreeMarker template error:
An error has occurred when reading existing sub-variable "grandparentRequirement"; see cause exception! The type of the containing value was: extended_hash+string (net.thucydides.core.requirements.reports.RequirementsOutcomes wrapped into f.e.b.StringModel)

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #if (requirements.grandparentRequirem...  [in template "freemarker/requirements.ftl" at line 172, column 17]
----

Java stack trace (for programmers):
----
freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
	at freemarker.ext.beans.BeanModel.get(BeanModel.java:199)
	at freemarker.core.Dot._eval(Dot.java:40)
	at freemarker.core.Expression.eval(Expression.java:78)
	at freemarker.core.Dot._eval(Dot.java:38)
	at freemarker.core.Expression.eval(Expression.java:78)
	at freemarker.core.MethodCall._eval(MethodCall.java:55)
	at freemarker.core.Expression.eval(Expression.java:78)
	at freemarker.core.Expression.evalToBoolean(Expression.java:124)
	at freemarker.core.Expression.evalToBoolean(Expression.java:110)
	at freemarker.core.ParentheticalExpression.evalToBoolean(ParentheticalExpression.java:31)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:46)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Environment.process(Environment.java:302)
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:42)
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:37)
	at net.thucydides.core.reports.html.BaseReportingTask.generateReportPage(BaseReportingTask.java:46)
	at net.thucydides.core.reports.html.RequirementsOverviewReportingTask.generateReports(RequirementsOverviewReportingTask.java:92)
	at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:32)
	at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1458)
	at freemarker.ext.beans.BeanModel.invokeThroughDescriptor(BeanModel.java:255)
	at freemarker.ext.beans.BeanModel.get(BeanModel.java:159)
	... 28 more
Caused by: java.lang.AbstractMethodError: net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(Lnet/thucydides/core/requirements/model/Requirement;)Lcom/google/common/base/Optional;
	at net.thucydides.core.requirements.reports.RequirementsOutcomes.parentRequirementOf(RequirementsOutcomes.java:176)
	at net.thucydides.core.requirements.reports.RequirementsOutcomes.getGrandparentRequirement(RequirementsOutcomes.java:171)
	... 35 more

**Comment by kamit78** [comment]
Following is the content of one of feature file

@issue:VA-182
Feature: About Developers

  Scenario: Serenity testing For developers
    Given Serenity code creation
    |Amit|
    |Peena|
    |Jeena|
    When Execute automation scripts

    Then Execute successfully without 'error'

**Comment by kamit78** [comment]
Serenity report display some Epic, stories , defect and Tasks but not the task that I have define in feature file i.e. VA-182

**Comment by kamit78** [comment]
Please help me to resolve it

**Comment by wakaleo** [comment]
What version of the jira plugin are you using?

**Comment by kamit78** [comment]
I'm using latest one i.e 1.1.3-rc.2 with following dependency

 `<properties>`
        <serenity.jira.plugin>1.1.3-rc.2</serenity.jira.plugin>
    `</properties>`

`<dependency>`
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jira-requirements-provider</artifactId>
            <version>${serenity.jira.plugin}</version>
`</dependency>`

**Comment by kamit78** [comment]
To reproduce it , I have added sample project source at following ticket 

https://github.com/serenity-bdd/serenity-cucumber/issues/76
