### ISSUE TITLE
Run-time errors using serenity

### ISSUE THREAD

**Issue by DenUlyanov** [serenity-bdd/serenity-cucumber#79]
While running my BDD test from IntelliJ IDEA 2016.3.4 I see scenario passed in IDEA but in logs scenario is mentioned as failed despite all steps are passed. 
Also while executing test I am getting following errors: 

`Failed scenarios:
/Users/dulyanov/Projects/../../src/test/resources/features/../any.feature:4 # Scenario: Test scenario

1 Scenarios (1 failed)
5 Steps (5 passed)
0m6.226s

java.lang.ExceptionInInitializerError
	at net.serenitybdd.cucumber.actors.StageDirector.endTheAct(StageDirector.java:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:223)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:211)
	at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:205)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.runtime.Runtime.run(Runtime.java:121)
	at cucumber.api.cli.Main.run(Main.java:36)
	at cucumber.api.cli.Main.main(Main.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for net.thucydides.core.webdriver.WebdriverManager was bound.
  while locating net.thucydides.core.webdriver.WebdriverManager

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:961)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
	at net.serenitybdd.cucumber.actors.Cast.<init>(Cast.java:20)
	at net.serenitybdd.cucumber.actors.OnStage.<clinit>(OnStage.java:9)
	... 22 more`

**Comment by wakaleo** [comment]
It could be a dependency conflict. Could you provide a sample project that reproduces the issue?

**Comment by wakaleo** [comment]
Closing due to lack of activity.
