### ISSUE TITLE
Test is passed but getting error in consoal Tag provider net.thucydides.core.requirements.PackageRequirementsTagProvider@278beade failure net.thucydides.core.requirements.CouldNotLoadRequirementsException

### ISSUE THREAD

**Issue by vaddiparthi** [serenity-bdd/serenity-cucumber#85]
[pool-1-thread-1] ERROR net.thucydides.core.model.TestOutcome - Tag provider net.thucydides.core.requirements.PackageRequirementsTagProvider@278beade failure
net.thucydides.core.requirements.CouldNotLoadRequirementsException
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.requirementPathsFromClassesInPackage(PackageRequirementsTagProvider.java:168)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.requirementPathsStartingFrom(PackageRequirementsTagProvider.java:156)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.requirementsReadFromClasspath(PackageRequirementsTagProvider.java:117)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.fetchRequirements(PackageRequirementsTagProvider.java:100)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.getRequirements(PackageRequirementsTagProvider.java:92)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.getRequirementFor(PackageRequirementsTagProvider.java:241)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.getTagsFor(PackageRequirementsTagProvider.java:261)
	at net.thucydides.core.model.TestOutcome.getTagsUsingTagProviders(TestOutcome.java:1492)
	at net.thucydides.core.model.TestOutcome.getTags(TestOutcome.java:1477)
	at net.thucydides.core.model.TestOutcome.addTags(TestOutcome.java:1522)
	at net.thucydides.core.steps.BaseStepListener.testFinished(BaseStepListener.java:371)
	at net.thucydides.core.steps.StepEventBus.testFinished(StepEventBus.java:250)
	at net.serenitybdd.jbehave.SerenityReporter.afterScenario(SerenityReporter.java:619)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterScenario(DelegatingStoryReporter.java:43)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterScenario(ConcurrentStoryReporter.java:176)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:890)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:811)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:784)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:416)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:387)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:291)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:265)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - [92m

(AfterStories)

Generating reports view to 'C:\Users\E002979\Documents\BridgeStone\qa-automation-seed-project\target\jbehave' using formats '[stats, console, html, xml, serenityreporter, junitscenarioreporter]' and view properties '{decorateNonHtml=true}'
Reports view generated with 2 stories (of which 0 pending) containing 1 scenarios (of which 0 pending)
Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 35.138 sec <<< FAILURE! - in com.vml.serenity.BridgestoneCommercialHomePage
com.vml.serenity.BridgestoneCommercialHomePage  Time elapsed: 1.453 sec  <<< ERROR!
java.lang.RuntimeException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)

**Comment by wakaleo** [comment]
What version of Serenity are you using?

**Comment by vaddiparthi** [comment]
<serenity.version>1.1.42</serenity.version>
		<serenity.jbehave.version>1.13.0</serenity.jbehave.version>

**Comment by wakaleo** [comment]
Could you try with the latest versions?

**Comment by vaddiparthi** [comment]
The same version used in other system and its working fine...somehow, am only getting error logs in console,  even framework is same.

**Comment by wakaleo** [comment]
As this is an open source project, we don't provide non-commerical support for older versions. If the problem occurs with 1.4.0, please feel free to reopen this issue.

**Comment by vaddiparthi** [comment]
I tried with below version as well but still the issue not resolved :

<serenity.version>1.4.1-rc.2</serenity.version>

**Comment by wakaleo** [comment]
Can you provide the stack dump with this version, and if possible a project that reproduces the issue.

**Comment by vaddiparthi** [comment]
[pool-1-thread-1] ERROR net.thucydides.core.model.TestOutcome - Tag provider net.thucydides.core.requirements.PackageRequirementsTagProvider@7161fc36 failure
net.thucydides.core.requirements.CouldNotLoadRequirementsException
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.requirementPathsFromClassesInPackage(PackageRequirementsTagProvider.java:168)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.requirementPathsStartingFrom(PackageRequirementsTagProvider.java:156)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.requirementsReadFromClasspath(PackageRequirementsTagProvider.java:117)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.fetchRequirements(PackageRequirementsTagProvider.java:100)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.getRequirements(PackageRequirementsTagProvider.java:92)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.getRequirementFor(PackageRequirementsTagProvider.java:241)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.getTagsFor(PackageRequirementsTagProvider.java:261)
	at net.thucydides.core.model.TestOutcome.getTagsUsingTagProviders(TestOutcome.java:1492)
	at net.thucydides.core.model.TestOutcome.getTags(TestOutcome.java:1477)
	at net.thucydides.core.model.TestOutcome.addTags(TestOutcome.java:1522)
	at net.thucydides.core.steps.BaseStepListener.testFinished(BaseStepListener.java:371)
	at net.thucydides.core.steps.StepEventBus.testFinished(StepEventBus.java:250)
	at net.serenitybdd.jbehave.SerenityReporter.afterScenario(SerenityReporter.java:619)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterScenario(DelegatingStoryReporter.java:43)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterScenario(ConcurrentStoryReporter.java:176)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:890)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:811)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:784)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:416)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:387)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:291)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:265)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vaddiparthi** [comment]
Above is the stack trace and am using Jbehave with serenity framework. where I have scenarios written in story file

**Comment by wakaleo** [comment]
It's a classloader problem of some kind. Is there any other stack trace that follows this one?

**Comment by vaddiparthi** [comment]
com.vml.serenity.ContactUs  Time elapsed: 2.179 sec  <<< ERROR!
java.lang.RuntimeException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:181)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:162)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:111)
	at net.serenitybdd.jbehave.SerenityReporter.generateReports(SerenityReporter.java:525)
	at net.serenitybdd.jbehave.SerenityReporter.afterStory(SerenityReporter.java:502)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:122)
	at org.jbehave.core.embedder.PerformableTree.performBeforeOrAfterStories(PerformableTree.java:435)
	at org.jbehave.core.embedder.StoryManager.performStories(StoryManager.java:130)
	at org.jbehave.core.embedder.StoryManager.runStories(StoryManager.java:107)
	at org.jbehave.core.embedder.StoryManager.runStoriesAsPaths(StoryManager.java:86)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:213)
	at net.serenitybdd.jbehave.embedders.ExtendedEmbedder.runStoriesAsPaths(ExtendedEmbedder.java:60)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:175)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
Caused by: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@d737b89
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:222)
	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:34)
	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:156)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: net.thucydides.core.requirements.CouldNotLoadRequirementsException: null
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.requirementPathsFromClassesInPackage(PackageRequirementsTagProvider.java:168)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.requirementPathsStartingFrom(PackageRequirementsTagProvider.java:156)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.requirementsReadFromClasspath(PackageRequirementsTagProvider.java:117)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.fetchRequirements(PackageRequirementsTagProvider.java:100)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.getRequirements(PackageRequirementsTagProvider.java:92)
	at net.thucydides.core.requirements.MultiSourceRequirementsService.getRequirements(MultiSourceRequirementsService.java:45)
	at net.thucydides.core.requirements.BaseRequirementsService.getRequirementTypes(BaseRequirementsService.java:193)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:130)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:96)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:220)
	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:34)
	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:156)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wakaleo** [comment]
Unfortunately the underlying exception isn't providing an error message, so it is very hard to know what is happening - your best bet is to place a breakpoint on line 168 of the PackageRequirementsTagProvider class and see what exception is being thrown.

**Comment by wakaleo** [comment]
Closing as this is not related to serenity-cucumber. Please reopen under serenity-jbehave if you are still having the issue with the latest versions.

**Comment by nayods** [comment]
you are right it is a cucumber one. please just add the @tag to your cucumber feature file
